### PR TITLE
Complete chapter 1

### PR DESCRIPTION
**Pull request by OxSon**
### Solutions for Chapter 1

This was harder than I thought it would be. Lots of corner cases for `lastDigit` that I did not consider until seeing the tests fail. Thanks for setting this up!

cc @vrom911 @chshersh

### CODE REVIEW

**Comment by vrom911** [comment]
Sorry, @OxSon ! Didn't notice this one first, so I write my review in here: https://github.com/kowainik/learn4haskell/pull/64

⚠️ By the way, per new rules of the Hacktoberfest event, you would need to add the `hacktoberfest` topic to this fork repo:

* https://hacktoberfest.digitalocean.com/hacktoberfest-update

All previous contributions are legit, but from now on it should have the label to participate.

**Review by vrom911 — APPROVED** [review]
As per my review in the main repo, Chapter 1 is ready to be merged 👍🏼 Great job! 

You can open another PR with the Chapter 2 solutions 🙂

**Comment by OxSon** [comment]
Thank you @vrom911 ! I added the `hacktoberfest` topic. Do you know if this PR will count now or no because it was created before i added the topic?

**Comment by vrom911** [comment]
I think that it would count as it was created on before October 3, 2020 at 12:00:00 UTC.
At least, this is what I think of the new rules 🤔 

Anyway, you had a PR opened into kowainik repo, which had the `hacktoberfest` topic from the start, so you should be safe 🙂 

I would suggest double-checking the dashboard at https://hacktoberfest.digitalocean.com/profile

**Pull request merged**
